//
//  NoteBrowserEditorView.swift
//  NoteCast
//
//  Main note read/edit surface.
//

import SwiftUI

/// Display state for the selected note.
enum EditorDisplayMode: Hashable {
    case preview
    case edit
}

/// Main read/edit surface for a single note.
struct NoteBrowserEditorView: View {
    let note: Note
    let folders: [NoteFolder]
    @ObservedObject var commandBridge: NoteBrowserEditorCommandBridge
    @Binding var editorMode: EditorDisplayMode
    let save: (_ noteID: UUID, _ title: String, _ text: String, _ folderID: UUID?) -> Bool

    @AppStorage("NoteBrowser.previewColorScheme") private var previewColorScheme: MarkdownPreviewColorScheme = .light

    @State private var titleDraft: String
    @State private var bodyDraft: String
    @State private var folderIDDraft: UUID?
    @State private var statusMessage: String?

    /// HTML generated by Swift Markdown for the preview pane.
    ///
    /// We keep the rendered HTML in state so the WebView only reloads when the
    /// user switches to Preview, edits the title while previewing, changes the
    /// preview appearance, or the note reloads from disk.
    @State private var previewHTML: String

    init(
        note: Note,
        folders: [NoteFolder],
        commandBridge: NoteBrowserEditorCommandBridge,
        editorMode: Binding<EditorDisplayMode>,
        save: @escaping (_ noteID: UUID, _ title: String, _ text: String, _ folderID: UUID?) -> Bool
    ) {
        self.note = note
        self.folders = folders
        self.commandBridge = commandBridge
        self._editorMode = editorMode
        self.save = save
        self._titleDraft = State(initialValue: note.displayTitle)
        self._bodyDraft = State(initialValue: note.text)
        self._folderIDDraft = State(initialValue: note.folder?.uuid)
        self._previewHTML = State(initialValue: MarkdownPreviewHTML.documentHTML(
            markdown: note.text,
            title: note.displayTitle,
            colorScheme: .light
        ))
    }

    private var hasChanges: Bool {
        titleDraft != note.displayTitle
            || bodyDraft != note.text
            || folderIDDraft != note.folder?.uuid
    }

    var body: some View {
        VStack(spacing: 0) {
            editorHeader
            editorBody
            editorFooter
        }
        .onAppear {
            renderPreview()
            updateCommandBridge()
        }
        .onDisappear {
            commandBridge.reset()
        }
        .onChange(of: hasChanges) { _, _ in
            updateCommandBridge()
        }
        .onChange(of: editorMode) { _, newMode in
            if newMode == .preview {
                renderPreview()
            }
        }
        .onChange(of: titleDraft) { _, _ in
            if editorMode == .preview {
                renderPreview()
            }
        }
        .onChange(of: previewColorScheme) { _, _ in
            if editorMode == .preview {
                renderPreview()
            }
        }
        .onChange(of: note.updated_at) { _, _ in
            // If another window or the CLI changed this note while it is open,
            // refresh the drafts to match the newly fetched model object.
            resetDrafts()
        }
    }

    @ViewBuilder
    private var editorBody: some View {
        if editorMode == .preview {
            previewBody
        } else {
            editBody
        }
    }

    private var previewBody: some View {
        MarkdownPreviewWebView(html: previewHTML, colorScheme: previewColorScheme)
            .accessibilityIdentifier("NoteBrowser.previewWebView")
            .frame(maxWidth: .infinity, maxHeight: .infinity)
            .background(Color(nsColor: .textBackgroundColor).opacity(0.82))
            .clipShape(RoundedRectangle(cornerRadius: 8, style: .continuous))
            .padding(.horizontal, 24)
            .padding(.bottom, 14)
    }

    private var editBody: some View {
        TextEditor(text: $bodyDraft)
            .font(.system(.body, design: .monospaced))
            .scrollContentBackground(.hidden)
            .overlay(alignment: .topLeading) {
                if bodyDraft.isEmpty {
                    Text("Write Markdown here...")
                        .foregroundStyle(.tertiary)
                        .padding(.top, 8)
                        .padding(.leading, 6)
                        .allowsHitTesting(false)
                }
            }
            .frame(maxWidth: .infinity, maxHeight: .infinity)
            .padding(12)
            .background(
                Color(nsColor: .textBackgroundColor).opacity(0.82),
                in: RoundedRectangle(cornerRadius: 8, style: .continuous)
            )
            .padding(.horizontal, 24)
            .padding(.bottom, 14)
    }

    private var editorHeader: some View {
        VStack(alignment: .leading, spacing: 16) {
            HStack(alignment: .top, spacing: 16) {
                VStack(alignment: .leading, spacing: 10) {
                    titleView

                    HStack(spacing: 10) {
                        metadataPill(systemImage: "calendar", text: "Created \(note.created_at.formatted(date: .abbreviated, time: .shortened))")
                        metadataPill(systemImage: "clock", text: "Updated \(note.updated_at.formatted(date: .abbreviated, time: .shortened))")
                        metadataPill(systemImage: "keyboard", text: note.created_via)
                    }
                }

                Spacer(minLength: 20)

                HStack(spacing: 8) {
                    folderPicker
                    previewColorSchemePicker
                }
            }
        }
        .padding(.horizontal, 24)
        .padding(.top, 22)
        .padding(.bottom, 14)
    }

    @ViewBuilder
    private var titleView: some View {
        if editorMode == .preview {
            Text(Note.cleanTitle(titleDraft) ?? note.displayTitle)
                .font(.largeTitle.bold())
                .lineLimit(2)
                .frame(maxWidth: .infinity, alignment: .leading)
        } else {
            TextField("Title", text: $titleDraft)
                .font(.largeTitle.bold())
                .textFieldStyle(.plain)
        }
    }

    private var folderPicker: some View {
        Picker("Folder", selection: $folderIDDraft) {
            Label("Unfiled", systemImage: "tray")
                .tag(Optional<UUID>.none)

            ForEach(folders) { folder in
                if let folderID = folder.uuid {
                    Label(folder.displayName, systemImage: "folder")
                        .tag(Optional(folderID))
                }
            }
        }
        .pickerStyle(.menu)
        .frame(width: 210)
    }

    private var previewColorSchemePicker: some View {
        Picker("Preview Appearance", selection: $previewColorScheme) {
            Image(systemName: "sun.max")
                .tag(MarkdownPreviewColorScheme.light)
                .accessibilityLabel("Light Preview")
            Image(systemName: "moon")
                .tag(MarkdownPreviewColorScheme.dark)
                .accessibilityLabel("Dark Preview")
        }
        .pickerStyle(.segmented)
        .labelsHidden()
        .controlSize(.small)
        .frame(width: 76)
        .help("Preview appearance")
        .accessibilityIdentifier("NoteBrowser.previewColorSchemeSegmentedControl")
    }

    private var editorFooter: some View {
        HStack(spacing: 10) {
            if let statusMessage {
                Label(statusMessage, systemImage: "checkmark.circle.fill")
                    .foregroundStyle(.secondary)
                    .font(.callout)
            } else {
                Text("Cmd+S saves changes")
                    .font(.callout)
                    .foregroundStyle(.secondary)
            }

            Spacer()

            Button("Revert") {
                resetDrafts()
            }
            .disabled(!hasChanges)

            Button {
                saveDrafts()
            } label: {
                Label("Save", systemImage: "checkmark")
            }
            .buttonStyle(.borderedProminent)
            .disabled(!hasChanges)
            .keyboardShortcut("s", modifiers: [.command])
        }
        .padding(.horizontal, 24)
        .padding(.bottom, 18)
    }

    private func metadataPill(systemImage: String, text: String) -> some View {
        Label(text, systemImage: systemImage)
            .font(.caption)
            .foregroundStyle(.secondary)
            .padding(.horizontal, 10)
            .padding(.vertical, 6)
            .background(.thinMaterial, in: Capsule())
    }

    private func renderPreview() {
        previewHTML = MarkdownPreviewHTML.documentHTML(
            markdown: bodyDraft,
            title: Note.cleanTitle(titleDraft) ?? note.displayTitle,
            colorScheme: previewColorScheme
        )
    }

    private func saveDrafts() {
        guard let noteID = note.uuid else { return }

        if save(noteID, titleDraft, bodyDraft, folderIDDraft) {
            statusMessage = "Saved"
            updateCommandBridge()
        }
    }

    private func resetDrafts() {
        titleDraft = note.displayTitle
        bodyDraft = note.text
        folderIDDraft = note.folder?.uuid
        statusMessage = nil

        if editorMode == .preview {
            renderPreview()
        }

        updateCommandBridge()
    }

    private func updateCommandBridge() {
        commandBridge.update(
            canSave: hasChanges,
            canRevert: hasChanges,
            save: saveDrafts,
            revert: resetDrafts
        )
    }
}
